import type { JSX } from 'preact';
import { SITE_BASE_URL } from '../common/siteBaseUrl';
import { ToolArticleSection, ToolFaqList, type ToolFaqItem } from '../common/tool-article/ToolArticle';

function createPlainTextFaqItem(question: string, answer: string): ToolFaqItem {
    return {
        question,
        answer,
        structuredDataAnswer: answer
    };
}

export const FAQ_ITEMS: ToolFaqItem[] = [
    createPlainTextFaqItem(
        'What is a QR code?',
        'A QR code, short for Quick Response code, is a two-dimensional barcode that stores data such as URLs, contact details, or plain text. Most smartphone cameras can scan QR codes directly and open or display the encoded information.'
    ),
    createPlainTextFaqItem(
        'How do I create a QR code with this tool?',
        'Enter the text or URL you want to encode, optionally adjust the size, margin, and error correction level, then download the generated PNG. The preview updates automatically as you change the input or settings.'
    ),
    createPlainTextFaqItem(
        'Can I customize my QR code with this tool?',
        'Yes. You can customize the generated QR code by changing its size, quiet-zone margin, and error correction level. This version does not support adding logos or changing colors.'
    ),
    createPlainTextFaqItem(
        'Is this QR code generator free to use?',
        'Yes. The CodeSamplez QR Code Generator is completely free to use with no signup or license required.'
    ),
    createPlainTextFaqItem(
        'How can I scan a QR code?',
        'Open your smartphone camera or QR scanner app, point it at the QR code, and tap the prompt that appears. Most modern phones support QR scanning directly from the default camera app.'
    ),
    createPlainTextFaqItem(
        'Do the QR codes expire?',
        'No. The QR codes generated by this tool do not expire. They will continue working as long as the encoded destination or text remains valid.'
    ),
    createPlainTextFaqItem(
        'Can I use these QR codes for commercial purposes?',
        'Yes. You can use QR codes created with this tool for personal, educational, or commercial purposes without restrictions from the generator itself.'
    ),
    createPlainTextFaqItem(
        'Is there a limit to how many QR codes I can generate?',
        'No. There is no usage limit imposed by this tool. You can generate as many QR codes as you need.'
    )
];

export function QRCodeGeneratorIntro(): JSX.Element {
    return (
        <section className="c-tool-article c-tool-article--intro c-surface-card" aria-labelledby="qr-code-generator-intro-heading">
            <div className="c-tool-article__content">
                <h2 id="qr-code-generator-intro-heading" className="c-tool-article__eyebrow">About This Tool</h2>
                <p className="c-tool-article__lead">
                    The CodeSamplez QR Code Generator is a <strong>free online QR code creator</strong> for turning
                    text, links, contact details, or other payloads into scannable QR codes. It renders codes directly
                    in your browser and lets you adjust <strong>size</strong>, <strong>quiet zone</strong>, and{' '}
                    <strong>error correction</strong> before downloading a PNG.
                </p>
            </div>
        </section>
    );
}

export function QRCodeGeneratorArticle(): JSX.Element {
    return (
        <section className="c-tool-article c-surface-card" aria-labelledby="qr-code-generator-article-heading">
            <div className="c-tool-article__content">
                <h2 id="qr-code-generator-article-heading" className="c-tool-article__sr-only">QR Code Generator Guide</h2>

                <ToolArticleSection id="how-to-generate-qr-code" title="How To Generate QR Code With This Tool:">
                    <ol>
                        <li>
                            <strong>Enter text or URL</strong>. You can encode website links, plain text, contact data,
                            Wi-Fi credentials, or any other QR-compatible payload.
                        </li>
                        <li>
                            <strong>Customize the configuration</strong>. Adjust the output size, quiet-zone margin,
                            and error correction level to fit your scanning and print requirements.
                        </li>
                        <li>
                            <strong>Download the PNG</strong>. The QR code updates in real time while you edit, and
                            you can save the final image with one click.
                        </li>
                    </ol>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-advanced-usage" title="Advanced Usage">
                    <ul>
                        <li><strong>For URLs:</strong> The QR code typically opens the target link when scanned.</li>
                        <li><strong>For plain text:</strong> Scanning displays the encoded message directly on the device.</li>
                        <li><strong>For contact information:</strong> Use a valid vCard payload for better compatibility.</li>
                        <li><strong>For Wi-Fi credentials:</strong> Use the format <code>WIFI:T:WPA;S:SSID;P:password;;</code>.</li>
                    </ul>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-features" title="QR Code Generator Supported Features">
                    <ul>
                        <li><strong>Generate QR codes from text or URLs</strong> without requiring signup or installation.</li>
                        <li><strong>Customize size</strong> for compact embeds or large printable outputs.</li>
                        <li><strong>Adjust quiet-zone margin</strong> to improve scan reliability across different layouts.</li>
                        <li><strong>Choose an error correction level</strong> from L, M, Q, or H depending on your tolerance for damage or obstruction.</li>
                        <li><strong>Download PNG output</strong> for reuse in documents, presentations, packaging, or signage.</li>
                        <li><strong>Preview changes instantly</strong> as you edit the payload or settings.</li>
                    </ul>

                    <div className="c-tool-article__cta-row">
                        <a className="c-button" href={SITE_BASE_URL}>
                            Explore More Dev Tools
                        </a>
                    </div>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-technology" title="Technology">
                    <p>
                        This tool uses JavaScript to generate QR code matrices and the browser canvas API to render the
                        final image. Everything happens locally in the page, which keeps generation fast and avoids
                        sending your data to a server.
                    </p>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-error-handling" title="Error Handling">
                    <ul>
                        <li>Rejects empty input and prompts for text or a URL before generation.</li>
                        <li>Surfaces payload-length errors when the selected correction level cannot fit the content.</li>
                        <li>Lets you recover by shortening the input or changing configuration values.</li>
                    </ul>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-privacy" title="Privacy & Security">
                    <ul>
                        <li>100% client-side processing: QR code generation happens in your browser.</li>
                        <li>No data storage: your text is not uploaded or persisted by the tool.</li>
                        <li>Works offline after the initial page load in capable browsers.</li>
                        <li>No external services are required at generation time.</li>
                    </ul>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-browser-compatibility" title="Browser Compatibility">
                    <p>The tool works in modern browsers that support:</p>
                    <ul>
                        <li>HTML5 Canvas API</li>
                        <li>File download support for PNG export</li>
                        <li>ES6+ JavaScript features</li>
                    </ul>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-feedback" title="Feedback">
                    <p>
                        Have a bug report, feature request, or workflow improvement for the QR generator? Please{' '}
                        <a href="https://codesamplez.com/contact">contact us</a>.
                    </p>
                </ToolArticleSection>

                <ToolArticleSection id="qr-code-generator-faqs" title="Frequently Asked Questions (FAQs)">
                    <ToolFaqList items={FAQ_ITEMS} />
                </ToolArticleSection>
            </div>
        </section>
    );
}
